function OUT = computeEqDelPartials(constants, COE, dir)
a = COE(1); e = COE(2); I = COE(3); O = COE(4); w = COE(5); M = COE(6);
if dir == 0
    L = sqrt(constants.mu*a);
    G = L * sqrt(1-e^2);
    H = G * cos(I);
    dEqdCOE = [1,          0,                           0,                0,             0, 0;...
            0, sin(O + w),                           0,     e*cos(O + w),  e*cos(O + w), 0;...
            0, cos(O + w),                           0,    -e*sin(O + w), -e*sin(O + w), 0;...
            0,          0, sin(O)*(tan(I/2)^2/2 + 1/2),  tan(I/2)*cos(O),             0, 0;...
            0,          0, cos(O)*(tan(I/2)^2/2 + 1/2), -tan(I/2)*sin(O),             0, 0;...
            0,          0,                           0,                1,             1, 1];
    dCOEdDel = [0, 0, 0, (34359738368*L)/6847903441654645,                            0,                          0;...
                0, 0, 0,    G^2/(L^3*(1 - G^2/L^2)^(1/2)), -G/(L^2*(1 - G^2/L^2)^(1/2)),                          0;...
                0, 0, 0,                                0,  H/(G^2*(1 - H^2/G^2)^(1/2)), -1/(G*(1 - H^2/G^2)^(1/2));...
                0, 0, 1,                                0,                            0,                          0;...
                0, 1, 0,                                0,                            0,                          0;...
                1, 0, 0,                                0,                            0,                          0];
    dEqdDel = dEqdCOE * dCOEdDel;
    OUT = dEqdDel;
    
else
    dEqdCOE = [1,          0,                           0,                0,             0, 0;...
            0, sin(O + w),                           0,     e*cos(O + w),  e*cos(O + w), 0;...
            0, cos(O + w),                           0,    -e*sin(O + w), -e*sin(O + w), 0;...
            0,          0, sin(O)*(tan(I/2)^2/2 + 1/2),  tan(I/2)*cos(O),             0, 0;...
            0,          0, cos(O)*(tan(I/2)^2/2 + 1/2), -tan(I/2)*sin(O),             0, 0;...
            0,          0,                           0,                1,             1, 1];
    dCOEdEq = dEqdCOE \ eye(6);
    dDeldCOE = [                                                                                               0,                                                                    0,                                                                0, 0, 0, 1;...
                                                                                                               0,                                                                    0,                                                                0, 0, 1, 0;...
                                                                                                               0,                                                                    0,                                                                0, 1, 0, 0;...
                                         6847903441654645/(34359738368*((6847903441654645*a)/17179869184)^(1/2)),                                                                    0,                                                                0, 0, 0, 0;...
                       (6847903441654645*(1 - e^2)^(1/2))/(34359738368*((6847903441654645*a)/17179869184)^(1/2)),        -(e*((6847903441654645*a)/17179869184)^(1/2))/(1 - e^2)^(1/2),                                                                0, 0, 0, 0;...
                (6847903441654645*cos(I)*(1 - e^2)^(1/2))/(34359738368*((6847903441654645*a)/17179869184)^(1/2)), -(e*cos(I)*((6847903441654645*a)/17179869184)^(1/2))/(1 - e^2)^(1/2), -sin(I)*(1 - e^2)^(1/2)*((6847903441654645*a)/17179869184)^(1/2), 0, 0, 0];
    dDeldEq = dDeldCOE * dCOEdEq;
    OUT = dDeldEq;
end

end


% l = M;
% g = w;
% h = O;
    
% COE = [6800;0.5;1;0;0;0];
% dir = 0;
% constants.mu = 398600.4415;


% syms a e I O w M
% vars = [a;e;I;O;w;M];

% 
% 
% dEqdDel = [0,             0,                0,                 (34359738368*((6847903441654645*a)/17179869184)^(1/2))/6847903441654645,                                                                                                      0,                                                                                                0;...
%             0,  e*cos(O + w),     e*cos(O + w),                    -(sin(O + w)*(e^2 - 1))/(e*((6847903441654645*a)/17179869184)^(1/2)),                             -(sin(O + w)*(1 - e^2)^(1/2))/(e*((6847903441654645*a)/17179869184)^(1/2)),                                                                                                0;...
%             0, -e*sin(O + w),    -e*sin(O + w),                    -(cos(O + w)*(e^2 - 1))/(e*((6847903441654645*a)/17179869184)^(1/2)),                             -(cos(O + w)*(1 - e^2)^(1/2))/(e*((6847903441654645*a)/17179869184)^(1/2)),                                                                                                0;...
%             0,             0,  tan(I/2)*cos(O), -(cos(I)*sin(O)*(tan(I/2)^2/2 + 1/2))/(sin(I)*((6847903441654645*a)/17179869184)^(1/2)), (cos(I)*sin(O)*(tan(I/2)^2/2 + 1/2))/(sin(I)*(1 - e^2)^(1/2)*((6847903441654645*a)/17179869184)^(1/2)), -(sin(O)*(tan(I/2)^2/2 + 1/2))/(sin(I)*(1 - e^2)^(1/2)*((6847903441654645*a)/17179869184)^(1/2));...
%             0,             0, -tan(I/2)*sin(O), -(cos(I)*cos(O)*(tan(I/2)^2/2 + 1/2))/(sin(I)*((6847903441654645*a)/17179869184)^(1/2)), (cos(I)*cos(O)*(tan(I/2)^2/2 + 1/2))/(sin(I)*(1 - e^2)^(1/2)*((6847903441654645*a)/17179869184)^(1/2)), -(cos(O)*(tan(I/2)^2/2 + 1/2))/(sin(I)*(1 - e^2)^(1/2)*((6847903441654645*a)/17179869184)^(1/2));...
%             1,             1,                1,                                                                                       0,                                                                                                      0,                                                                                                0];
% 
% if dir == 1
%     OUT = dEqdDel;
% else
%     OUT = dEqdDel \ eye(6);   
% end


%dDeldCOE =  [diff(l,a) diff(l,e) diff(l,I) diff(l,O) diff(l,w) diff(l,M);...
%     diff(g,a) diff(g,e) diff(g,I) diff(g,O) diff(g,w) diff(g,M);...
%     diff(h,a) diff(h,e) diff(h,I) diff(h,O) diff(h,w) diff(h,M);...
%     diff(L,a) diff(L,e) diff(L,I) diff(L,O) diff(L,w) diff(L,M);...
%     diff(G,a) diff(G,e) diff(G,I) diff(G,O) diff(G,w) diff(G,M);...
%     diff(H,a) diff(H,e) diff(H,I) diff(H,O) diff(H,w) diff(H,M)];


%dEqdCOE = [diff(a,a) diff(a,e) diff(a,I) diff(a,O) diff(a,w) diff(a,M);...
%     diff(hE,a) diff(hE,e) diff(hE,I) diff(hE,O) diff(hE,w) diff(hE,M);...
%     diff(k,a) diff(k,e) diff(k,I) diff(k,O) diff(k,w) diff(k,M);...
%     diff(p,a) diff(p,e) diff(p,I) diff(p,O) diff(p,w) diff(p,M);...
%     diff(q,a) diff(q,e) diff(q,I) diff(q,O) diff(q,w) diff(q,M);...
%     diff(lam,a) diff(lam,e) diff(lam,I) diff(lam,O) diff(lam,w) diff(lam,M)];

% dCOEdEq = [diff(a,a) diff(a,hE) diff(a,k) diff(a,p) diff(a,q) diff(a,lam);...
%     diff(e,a) diff(e,hE) diff(e,k) diff(e,p) diff(e,q) diff(e,lam);...
%     diff(I,a) diff(I,hE) diff(I,k) diff(I,p) diff(I,q) diff(I,lam);...
%     diff(O,a) diff(O,hE) diff(O,k) diff(O,p) diff(O,q) diff(O,lam);...
%     diff(w,a) diff(w,hE) diff(w,k) diff(w,p) diff(w,q) diff(w,lam);...
%     diff(M,a) diff(M,hE) diff(M,k) diff(M,p) diff(M,q) diff(M,lam)];


%dCOEdDel =  [diff(a,l) diff(a,g) diff(a,h) diff(a,L) diff(a,G) diff(a,H);...
%     diff(e,l) diff(e,g) diff(e,h) diff(e,L) diff(e,G) diff(e,H);...
%     diff(I,l) diff(I,g) diff(I,h) diff(I,L) diff(I,G) diff(I,H);...
%     diff(O,l) diff(O,g) diff(O,h) diff(O,L) diff(O,G) diff(O,H);...
%     diff(w,l) diff(w,g) diff(w,h) diff(w,L) diff(w,G) diff(w,H);...
%     diff(M,l) diff(M,g) diff(M,h) diff(M,L) diff(M,G) diff(M,H)];


% hE = e * sin(w+O);
% k = e * cos(w+O);
% p = tan(I/2) * sin(O);
% q = tan(I/2) * cos(O);
% lam = M + w + O;
    
%     dCOEdEq = [1,                                                                       0,                                                                                                                            0,                                                                                                                                0,                                                                                                                                                                                                                                                                                                         0, 0;...
%             0,                            -(k*sign(k + hE*1i)*1i)/(imag(hE) - real(k)), - abs(k + hE*1i)/(imag(hE) - real(k)) - (k*abs(k + hE*1i))/(imag(hE) - real(k))^2 - (k*sign(k + hE*1i))/(imag(hE) - real(k)),                                                                                                                                0,                                                                                                                                                                                                                                                                                                         0, 0;...
%             0,                                                                       0,                                                                                                                            0, -(sign(q + p*1i)*real(q)*(imag(p) - real(q))*2i)/(abs(q + p*1i)^2*(real(q)^2 + (imag(q) + (imag(p) - real(q))/abs(q + p*1i))^2)), -(2*(imag(q) + (imag(p) - real(q))/abs(q + p*1i))^2*(1/(imag(q) + (imag(p) - real(q))/abs(q + p*1i)) + (real(q)*(1/abs(q + p*1i) + (sign(q + p*1i)*(imag(p) - real(q)))/abs(q + p*1i)^2))/(imag(q) + (imag(p) - real(q))/abs(q + p*1i))^2))/(real(q)^2 + (imag(q) + (imag(p) - real(q))/abs(q + p*1i))^2), 0;...
%             0,                                                                       0,                                                                                                                            0,                                                             -(imag(p) - real(q))/((imag(q) + real(p))^2 + (imag(p) - real(q))^2),                                                                                                                                                                                                                                      -(imag(q) + real(p))/((imag(q) + real(p))^2 + (imag(p) - real(q))^2), 0;...
%             0, -(imag(hE) - real(k))/((imag(k) + real(hE))^2 + (imag(hE) - real(k))^2),                                                      -(imag(k) + real(hE))/((imag(k) + real(hE))^2 + (imag(hE) - real(k))^2),                                                              (imag(p) - real(q))/((imag(q) + real(p))^2 + (imag(p) - real(q))^2),                                                                                                                                                                                                                                       (imag(q) + real(p))/((imag(q) + real(p))^2 + (imag(p) - real(q))^2), 0;...
%             0,  (imag(hE) - real(k))/((imag(k) + real(hE))^2 + (imag(hE) - real(k))^2),                                                       (imag(k) + real(hE))/((imag(k) + real(hE))^2 + (imag(hE) - real(k))^2),                                                                                                                                0,                                                                                                                                                                                                                                                                                                         0, 1];