function OUT = substitutePartials(IN, subPartialsInputs)
    r = subPartialsInputs(1); crLpart = subPartialsInputs(2); crGpart = subPartialsInputs(3);
    crHpart = subPartialsInputs(4); crlpart = subPartialsInputs(5); cfLpart = subPartialsInputs(6);
    cfGpart = subPartialsInputs(7); cfHpart = subPartialsInputs(8); cflpart = subPartialsInputs(9);
    TA = subPartialsInputs(10); cELpart = subPartialsInputs(11); cEGpart = subPartialsInputs(12); 
    cElpart = subPartialsInputs(13); cEHpart = subPartialsInputs(14); Ecc = subPartialsInputs(15);
    crLpartVal = subPartialsInputs(16); crGpartVal = subPartialsInputs(17); crHpartVal = subPartialsInputs(18);
    crlpartVal = subPartialsInputs(19); cfLpartVal = subPartialsInputs(20); cfGpartVal = subPartialsInputs(21);
    cfHpartVal = subPartialsInputs(22); cflpartVal = subPartialsInputs(23); cELpartVal = subPartialsInputs(24);
    cEGpartVal = subPartialsInputs(25); cElpartVal = subPartialsInputs(26); cEHpartVal = subPartialsInputs(27);
    IN = subs(IN, str2sym('diff(rfun(L, G, H, l), L)'),crLpart);
    IN = subs(IN, str2sym('diff(rfun(L, G, H, l), G)'),crGpart);
    IN = subs(IN, str2sym('diff(rfun(L, G, H, l), H)'),crHpart);
    IN = subs(IN, str2sym('diff(rfun(L, G, H, l), l)'),crlpart);
    IN = subs(IN, str2sym('rfun(L, G, H, l)'),r);
    IN = subs(IN, str2sym('diff(TAfun(L, G, H, l), L)'),cfLpart);
    IN = subs(IN, str2sym('diff(TAfun(L, G, H, l), G)'),cfGpart);
    IN = subs(IN, str2sym('diff(TAfun(L, G, H, l), H)'),cfHpart);
    IN = subs(IN, str2sym('diff(TAfun(L, G, H, l), l)'),cflpart);
    IN = subs(IN, str2sym('TAfun(L, G, H, l)'),TA);
    IN = subs(IN, str2sym('diff(Eccfun(L, G, H, l), L)'),cELpart);
    IN = subs(IN, str2sym('diff(Eccfun(L, G, H, l), G)'),cEGpart);
    IN = subs(IN, str2sym('diff(Eccfun(L, G, H, l), H)'),cEHpart);
    IN = subs(IN, str2sym('diff(Eccfun(L, G, H, l), l)'),cElpart);
    IN = subs(IN, str2sym('Eccfun(L, G, H, l)'),Ecc);
    IN = subs(IN, 'crLpart',crLpartVal);
    IN = subs(IN, 'crGpart',crGpartVal);
    IN = subs(IN, 'crHpart',crHpartVal);
    IN = subs(IN, 'crlpart',crlpartVal);
    IN = subs(IN, 'cfLpart',cfLpartVal);
    IN = subs(IN, 'cfGpart',cfGpartVal);
    IN = subs(IN, 'cfHpart',cfHpartVal);
    IN = subs(IN, 'cflpart',cflpartVal);
    IN = subs(IN, 'cELpart',cELpartVal);
    IN = subs(IN, 'cEGpart',cEGpartVal);
    IN = subs(IN, 'cEHpart',cEHpartVal);
    IN = subs(IN, 'cElpart',cElpartVal);
    OUT = IN;
end
